# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_nearest_neighbors <- function(X, X_dist, X_inds, k) {
    invisible(.Call('_rmi_get_nearest_neighbors', PACKAGE = 'rmi', X, X_dist, X_inds, k))
}

#' compute nearest neighbors according to infinity norm
#'
#' @param data matrix. Each row is an observation.
#' @param k integer. Number of neighbors to observe.
#' @return List of distances and indices of k nearest neighbors of each point in \code{data}.
#' @examples
#' X <- cbind(1:10)
#' nearest_neighbors(X,3)
#'
#' set.seed(123)
#' X <- cbind(runif(100),runif(100))
#' plot(X,pch=20)
#' points(X[3,1],X[3,2],col='blue',pch=19, cex=1.5)
#' nn <- nearest_neighbors(X,5)
#' a = X[nn$nn_inds[3,]+1,1]
#' b = X[nn$nn_inds[3,]+1,2]
#' points(a,b,col='red',pch=19, cex=1.5)
#'
#' @export
#'
nearest_neighbors <- function(data, k) {
    .Call('_rmi_nearest_neighbors', PACKAGE = 'rmi', data, k)
}

#' mutual information function
#'
#' @param x numeric vector
#' @param low lower bound
#' @param high upper bound
#' @param res bounded numeric vector
#' @return bounded numeric vector
#' @export
#'
knn_mi <- function(data, splits, options) {
    .Call('_rmi_knn_mi', PACKAGE = 'rmi', data, splits, options)
}

parse_split_vector <- function(splits, d, start_d, end_d) {
    invisible(.Call('_rmi_parse_split_vector', PACKAGE = 'rmi', splits, d, start_d, end_d))
}

